from youtube_transcript_api import YouTubeTranscriptApi

video_id = '-eev0Ysj6Qc'
transcripts = YouTubeTranscriptApi.list_transcripts(video_id)

# Retrieve the autogenerated transcript in Portuguese
auto_transcript = transcripts.find_generated_transcript(['pt'])

transcript = auto_transcript.fetch()

# Write the transcript to a file without timestamps
with open('transcript.txt', 'w') as file:
    for entry in transcript:
        file.write(f"{entry['text']}\n")